server:
  port: 8001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yaoo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

